### ISSUE TITLE
Console error in 1.0.4

### ISSUE THREAD

**Issue by WickedSchnitzel** [jacopouggeri/BearTrap#1]
[Error] [beartrap] An exception was thrown when trying to start the mod:
11.6.2024 16:33:31 [Error] [beartrap] Exception: Unable to cast object of type 'Vintagestory.Common.ModLogger' to type 'Vintagestory.Logger'.
   at BearTrap.BearTrapModSystem.StartServerSide(ICoreServerAPI api) in /Users/jacopouggeri/workspace/modding/VS/BearTrap/BearTrap/BearTrapModSystem.cs:line 26
   at Vintagestory.Common.ModLoader.TryRunModPhase(Mod mod, ModSystem system, ICoreAPI api, ModRunPhase phase) in VintagestoryLib\Common\API\ModLoader.cs:line 660
11.6.2024 16:33:31 [Error] Failed to start system BearTrap.BearTrapModSystem

**Comment by jacopouggeri** [comment]
Thanks, will solve soon. Does this happen always or only occasionally?
